app = "ileap-demo-api"
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = "ams"

[env]
PORT = "8000"
PRIMARY_REGION = "ams"

[build]
dockerfile = "Dockerfile"

[[services]]
internal_port = 8_000
protocol = "tcp"
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
timeout = "2s"
