on: [push]

name: iLEAP Data Model CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  sqlite3_smoke_test:
    name: SQLite3 smoke test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SQLITE3 Smoke Test
        working-directory: ileap-data-model/sql-example
        run: |
          sqlite3 < ileap.sql

  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: CI
        working-directory: ileap-data-model
        run: |
          cargo build
          cargo test

  generate_schema:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Generate schema
        run: |
          cargo run --bin ileap-data-model
